services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-slim
      args:
        NAROU_VERSION: 3.8.2
        AOZORAEPUB3_VERSION: 1.1.1b18Q
        UID: 1000
        GID: 1000
    image: narou
    user: narou
    command: ["narou", "web", "-np", "33000"]
    volumes:
      - .:/home/narou/novel:cached
    tty: true
    stdin_open: true
    ports:
      - "127.0.0.1:33000-33001:33000-33001"
